### ISSUE TITLE
Menu mobs not rendering

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/menucompanions#5] opened 2021-01-21 22:02 UTC
`Minecraft v1.16.5`
`Forge v36.0.1`
`Menu Companions v1.1`

Mobs are not rendering on the menu for me until I edit and then save the config file.

**Comment by ghost** [comment] 2021-01-22 04:31
Same issue of not rendering here.

`Minecraft 1.16.4`
`Forge 35.1.37`
`Menu Companions 1.1`

**Comment by Fuzss** [comment] 2021-02-03 14:42
You probably still have the old config file (`mobs.json` in the `config/menucompanions` directory) from v1.0.2. Delete that so it can be regenerated and report back if it works.

**Comment by ghost** [comment] 2021-02-05 04:17
Just tried that, still nothing rendering unfortunately.

**Comment by WenXin20** [comment] 2021-02-05 19:01
Same for me, the file regenerated, but still no mobs.

**Comment by ghost** [comment] 2021-02-05 21:41
There are only a couple of mods I have that I can immediately think of that would cause conflicts:
- Optifine
- FancyMenu

...I wonder if FancyMenu hooks into something that prevents MenuCompanions from hooking in to do its own work? Not sure how either mod achieves what they achieve, aha.

**Comment by WenXin20** [comment] 2021-02-05 21:47
I don't have Fancy Menu, but I do have Optifine. I also have Quark and Survive, both of which adds a button to the menu.

**Comment by ghost** [comment] 2021-02-05 21:47
I have Quark too - I never really considered that it could break the rendering but who knows.

How many mods do you have total? We should both post our mods lists for Fuzss so he can maybe pick out the common factor easier.

**Comment by WenXin20** [comment] 2021-02-05 22:01
Uhh, it's a lot. Although I kinda doubt it's quark. It's probably to do with the menu companions config not loading. If I change something in the config and save it, then mobs will appear.

**Comment by ghost** [comment] 2021-02-05 23:14
[mod-list_2021-02-06_09.52.12.txt](https://github.com/Fuzss/menucompanions/files/5935781/mod-list_2021-02-06_09.52.12.txt)
Genned a mod list using TellMe just in case it helps.

Also hmm that's interesting. Maybe a temp fix is just to change the config? Or does it only last for a single run?

**Comment by WenXin20** [comment] 2021-02-05 23:21
It only lasts a single run.

**Comment by Fuzss** [comment] 2021-02-09 23:42
How's [this](https://mega.nz/file/iBFiRZrT#dJULkzS7dmfkOk3QV5kWfCWMw4OneM8G--hw7KNLoEA) version working for you? Does everything load correctly?

**Comment by WenXin20** [comment] 2021-02-10 18:00
The menu mobs still don't appear, even after saving the config file. Also, the reload button appears even when ctrl is not being held, although it can't be clicked on until I hold down ctrl.

**Comment by Fuzss** [comment] 2021-02-10 18:19
Are you on Windows? How do the contents of the `config/menucompanions ` directory look like, what files does it have? Can you also send your `latest.log` please.

For the reload button that's probably Ice and Fire. I have no clue why they would want to turn every button visible.

**Comment by WenXin20** [comment] 2021-02-10 18:26
It has the menucompanions-client.toml and the mobs.json.
Here's the log: https://gist.github.com/WenXin20/20020c3669ce0dc0f829dbf91619af97

**Comment by Fuzss** [comment] 2021-02-10 19:00
[Here](https://mega.nz/file/WIkUkB4B#LhIw99jdyYFnS7C9Sn22aHpDceGCnmjLYhil0dkMpm0) is another version. It won't work either if the first one didn't, but it'll output a lot more information to the log. So please send `latest.log`!

**Comment by WenXin20** [comment] 2021-02-10 19:11
Thanks, I'll give it a try.

**Comment by Fuzss** [comment] 2021-02-10 19:25
Oh and please try delete the old `config/menucompanions` folder so it can be recreated. I think that might actually be the problem here.

**Comment by WenXin20** [comment] 2021-02-10 20:01
https://gist.github.com/WenXin20/43a069e550569b718211ae575e015d72

**Comment by Fuzss** [comment] 2021-02-10 20:09
Alright, thanks. So you indeed just have to delete the `menucompanions` folder.

**Comment by WenXin20** [comment] 2021-02-10 20:15
So I deleted the folder, pressed the refresh button, and then got a crash.
https://gist.github.com/WenXin20/40d86c44ff94accff2b5ce3f0a2a44a4

**Comment by Fuzss** [comment] 2021-02-10 20:27
Try to disable `use_player_list_name_in_tag` from the `Fabrication` mod.

**Comment by WenXin20** [comment] 2021-02-10 20:58
Yep, that stopped the crash, but I'm not seeing the player. The mobs are rendering though. :)

**Comment by Fuzss** [comment] 2021-02-11 08:33
Getting closer and closer...
Problem with players is a lot of mods hook into the rendering in unpredictable ways. Can you please test [this version](https://mega.nz/file/zVtWWTRY#BrnmpStppS2XFw77kIYzlS7FQbM8EKASTNfZ--RoA5U) for me, so we can find out why the player isn't rendering? It should crash when rendering the main menu, the crash-report is what I need then.

**Comment by ghost** [comment] 2021-02-11 08:55
This first linked version you provided worked for me!!

![image](https://user-images.githubusercontent.com/24266948/107616924-0ee09380-6ca3-11eb-8147-6b0846512817.png)

I did update some 33 mods before starting the pack too, I wonder if something was fixed on their end? This is what was updated:

![image](https://user-images.githubusercontent.com/24266948/107617040-494a3080-6ca3-11eb-819f-d72c7fea5e03.png)

**Comment by Fuzss** [comment] 2021-02-11 09:08
great, thanks for the feedback!
other mods don’t really have anything to do with this particular issue, that was solely caused by me. 
still waiting for @WenXin20 now so we can figure out why their player isn’t rendering

**Comment by ghost** [comment] 2021-02-11 09:55
Mhm! Let me know if I can be of any service still.

**Comment by ghost** [comment] 2021-02-11 14:54
Coming back as it has just occurred to me - @WenXin20 have you been deleting the MenuCompanions configuration folder when testing the new jars? That's something I also did before trying the test version that worked for me.

**Comment by Fuzss** [comment] 2021-02-11 17:15
The loading part is working fine. Only the player isn't rendering. That's usually caused by other mods hooking into the player renderer in unpredictable ways. I only want to find out which mod that is in @WenXin20 's case.

**Comment by WenXin20** [comment] 2021-02-11 19:05
Strangely enough, the player is rendering this time and there was no crash with v1.2.2b1.

**Comment by WenXin20** [comment] 2021-02-11 20:09
This time when the game was loaded the player did not render, although there was no crash.

**Comment by Fuzss** [comment] 2021-02-12 08:41
So everything seems to be working now. Great, so this can finally be closed.

**Closed as completed by Fuzss** 2021-02-12 08:41 UTC
